version: "3.7"

services:
  database_challange:
    image: postgres
    container_name: database_challange
    restart: always
    ports: 
      - 5432:5432
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=queries_challenge
    volumes: 
      - pgdata:/data/postgres

volumes: 
  pgdata:
    driver: local